<?php
//
/**
 * Implements hook_menu().
 */
function mp_service_menu() {
  $items['mp_service'] = array(
    'title' => 'valid&response',
    'page callback' => 'mp_service_response',
    'access callback' => TRUE,
  );
  $items['admin/config/mp_service'] = array(
    'title' => 'mp_service settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_service_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mp_service.admin.inc',
  );
  return $items;
}

function my_module_function($last_reply_code=0) {
  global $user;
  $my_data = &drupal_static(__FUNCTION__);
  if (!isset($my_data)) {
    if ($cache = cache_get('mp_service_'.$user->uid)) {
      $my_data = $cache->data;
    }
    else {
      // Do your expensive calculations here, and populate $my_data
      // with the correct stuff..
      // cache_set('my_module_data', $my_data, 'cache');
      cache_set('mp_service_'.$user->uid, $my_data, 'cache_mp_service', time() + 60);//1分钟内回复有效
    }
  }
  return $my_data;
}

function mp_service_response() {
  module_load_include('inc', 'mp_service', 'mp_service_adv');
  $options = array(
    'token'=> variable_get('mp_service_token', 'ybzx'),//填写你设定的key
  );
  $options = array(
    'token'=>'ybzx',
    'account'=>'xiangkeguo@gmail.com',
    'password'=>'mjk5nj'
  );
  $wechatObj = new Wechat($options);
  // $wechatObj->valid(); //注意, 应用验证通过后,可将此句注释掉, 但会降低网站安全性
  $type = $wechatObj->getRev()->getRevType();
  switch($type) {
    case Wechat::MSGTYPE_TEXT:
      $keyword =  trim($wechatObj->getRevContent());
      $FromUserName =  $wechatObj->getRev()->getRevFrom();
      $uid = mp_service_get_uid_by_name($FromUserName);
      if($uid) {
        $mp_service_records = mp_service_get_records($uid);
        // watchdog('mp_service_records', '<pre>'.print_r($mp_service_records,TRUE), array(), WATCHDOG_NOTICE, 'link');
        //15秒内回复任何字符都拒绝！
        if($keyword != '88' && $mp_service_records['last_cmd'] == '20' && (REQUEST_TIME - $mp_service_records['last_cmd_timestamp'] < 900)) {
          $contentStr = "请选择要发布的相片!\n回复【88】取消改指令！";
          $wechatObj->text($contentStr)->reply();
          exit;
        }
      }
      //以20开头的，发布内如的，如果没有绑定，直接回绝！
      if(substr($keyword, 0,2) == '20') {
        if(!$uid) {
          $contentStr = "未绑定！不可发送20开头的指令！\n回复【9】查看绑定帮助\n回复【5】良友今日广播";
          $wechatObj->text($contentStr)->reply();
          exit;
        }
      }
      switch ($keyword) {
        case '00':     
          $contentStr = "【1】玩法介绍\n【2】发布相片/心情\n【3】查看活跃用户\n【4】每日灵修广播\n【5】良友今日广播\n【110】推荐给好友？\n【5010】灵命日粮文字版new\n【5030】恋爱季节为您解读网络社交与圣经婚恋价值观\n广播指令为纯数字，请勿带*号。号和中括号\n";
          break;        
        case '88':     
          $contentStr = "指令已取消！\n【1】玩法介绍\n【2】发布相片/心情\n【3】查看活跃用户\n【4】好牧人灵修广播\n【5】良友今日广播";
          if($uid) 
            db_update('mp_service')
              ->fields(array(
                'last_cmd' => '88',
                'last_cmd_timestamp' => REQUEST_TIME,
              ))
              ->condition('uid', $uid)
              ->execute();
          break;
        case '1':
          $contentStr ="通过微信玩转永不止息？\n如果您是永不止息会员，\n回复【9】绑定后更多玩法\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【5010】灵命日粮文字版\n【5030】恋爱季节为您解读网络社交与圣经婚恋价值观\n【110】推荐帮助-如何推荐给好友？";
          break;
        case '2':
          $contentStr = "表达爱的心语,遥寄未来的TA!\n【20】发布照片\n【201】无主情话\n【202】时光隧道\n【203】独居生活\n【204】想对你说\n回复获得更详细发布说明\n 回复【00】进入主菜单\n回复【5】进入良友广播";
          // 【201】无主情话(随便说点情话)-38
          // 【202】时光隧道(分享我的过去)-39
          // 【203】独居生活(记录现在的生活)-40
          // 【204】想对你说(写给喜欢的人)-41
          break;
        case '20':
          // if(!$uid) {
          //   $contentStr = "您还没有与网站帐号绑定！暂时不能发相片！\n回复【9】查看绑定帮助";
          // }else
          {
            $contentStr = "请选择您要发布的相片\n(15秒内发送)\n";
            db_update('mp_service')
              ->fields(array(
                'last_cmd' => '20',
                'last_cmd_timestamp' => REQUEST_TIME,
              ))
              ->condition('uid', $uid)
              ->execute();
          }
          break;
        case '201':
          $contentStr = "(随便说点情话)请回复:【201+内容】\n比如：201今天天气好，心情不错，未来的你呢？\n即可发布【无主情话】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
          break;

        case '202':
          $contentStr = "(分享我的过去)请回复:【202+内容】\n比如：202记得大三那年，还没到夏至，我在湖边的操场上～\n即可发布【时光隧道】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
          break;

        case '203':
          $contentStr = "(记录现在的生活)请回复:【203+内容】\n比如：203明天开始，要去丰台跑市场了\n即可发布【独居生活】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
          break;

        case '204':
          $contentStr = "(写给喜欢的人)请回复:【204+内容】\n比如：204这个世界很浮躁，内心的需要早已被人们忽略掉！\n即可发布【想对你说】\n回复【9】查看绑定帮助\n回复【2】返回上级菜单";
          break;
        case '3':
          $contentStr =  "最近活跃的弟兄姊妹有：\n\t\t侯星光\n\t\t韩富军\n\t\t王露\n\t\t畅卢涛...\n\n回复【00】进入主菜单\n回复【5】进入良友广播\n 本功能测试开发中～";
          break;
        case '4':
          $contentStr =  "【520】喜乐的心\n【521】荒漠甘泉乐侣\n【522】静夜亮光\n【523】在天父怀中\n【524】灵命日粮\n回复【00】进入主菜单\n回复【5】良友广播\n";
          break;
        case '5':
          $contentStr =  "【500】长夜的牵引\n【501】灵命日粮\n【502】拥抱每一天\n【503】恋爱季节\n【504】幸福满家园^\n【505】亲情不断电*\n【506】欢乐卡洽碰\n【507】书香园地*\n【508】晨曦讲座\n【509】生活无国界\n回复【51】进入下一页\n回复【52】进入灵修版\n回复【00】进入主菜单\n广播指令为纯数字，请勿带*号。号和中括号\n回复【5030】恋爱季节为您解读网络社交与圣经婚恋价值观\n回复【110】推荐给好友";
          break;
        case '51':
          $contentStr =  "【510】无限飞行号\n 【511】i-radio爱广播^\n【512】i关怀心磁场\n【513】真理之光\n回复【5】进入上一页\n回复【00】进入主菜单\n带*节目为周一到周五\n带^节目为15分钟\n回复【5030】恋爱季节为您解读网络社交与圣经婚恋价值观\n回复【110】推荐给好友\n";
          break;
        case '52':
          $contentStr =  "【520】喜乐的心\n【521】荒漠甘泉乐侣\n【522】静夜亮光\n【523】在天父怀中\n【524】灵命日粮\n【525】真道分解\n回复【00】进入主菜单\n回复【5】良友广播\n回复【5030】恋爱季节为您解读网络社交与圣经婚恋价值观\n回复【110】推荐给好友\n";
          break;
        case '9':
          $contentStr =  "注意：此功能为http://yongbuzhixi.com会员才可以使用\n回复【900 个人邮箱 姓名】申请内测 注意中间空格\n就要绑定，请回复\n【91昵称?手机后四位】 \n》比如：91活水泉?1407\n》91后面的为您的昵称。\n》昵称后面的？号不能少哦！\n【900】如何查看用户昵称\n【901】如何查看手机信息\n【5】进入良友广播\n";
          break;
        case '900':
          $contentStr =  "Q:如何查看用户昵称？\n A:登录http://yongbuzhxi.com查看。\n回复【900 个人邮箱 姓名】申请内测\n注意中间空格\n【9】返回绑定菜单\n【00】返回主菜单\n【5】进入良友广播\n";
          break;
        case '901':
          $contentStr =  "Q:如何查看手机信息？\n A:注册的时候填写的\n如果在注册时没有填写，您可以到个人页面，点击：编辑->基本信息。\n回复【900 个人邮箱 姓名】申请内测,注意中间空格\n回复【9】返回绑定菜单\n回复【00】返回主菜单\n回复【5】进入良友广播\n";
          break;

        case '911':
          $contentStr =  "我很忙，但很愿意为您服务，请微信加bluesky_still\n把您使用到的问题发给我。\n或加永不止息会员QQ群：322-1989-01\n回复【00】返回主菜单\n回复【5】进入良友广播\n回复【119+内容】请求代祷团队祷告支持";
          break;
        case '119':
          $contentStr =  "我很忙，但很愿意为您服务，请微信加bluesky_still\n把您使用到的问题发给我。\n回复【00】返回主菜单\n回复【5】进入良友广播";
          break;
        case '110':
          // $html = file_get_html('http://pp2717153.weixin.pp.cc/18817_mini.html');
          // $items = $html->find('#links', 0);
          // foreach ($items->children as $key => $html) {
          //   $link = $html->find('a', 0);
          //   $Url = $link->attr['href'];
          //   $Title = trim($html->find('h2', 0)->plaintext);
          //   $Description = trim($html->find('p', 0)->plaintext);

          //   $picture = $html->find('img', 0);
          //   $PicUrl = $picture->attr['src'];
          //   $img = array(
          //     'Title'=> $Title,
          //     'Description'=>$Description,
          //     'PicUrl'=>$PicUrl,
          //     'Url'=>$Url
          //   );
          //   $news[] = $img; 
          // }
          $img = array(
              'Title'=> '微信玩转【永不止息】，良友一起来',
              'Description'=>'推荐永不止息给你的好友',
              'PicUrl'=>'http://www.yongbuzhixi.com/sites/all/themes/love/family_1.png',
              'Url'=>'http://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5ODQ4NjU4MA==&appmsgid=10000220&itemidx=1&sign=4fa7692a32ea607c2e8194e79f077644'
            );
          $news[] = $img;
          $img = array(
              'Title'=> '【永不止息】教您玩转微信',
              'Description'=>'转给你的好友吧，图片多，记得wifi下',
              'PicUrl'=>'http://www.yongbuzhixi.com/sites/all/themes/love/family_2.png',
              'Url'=>'http://mp.weixin.qq.com/mp/appmsg/show?__biz=MjM5ODQ4NjU4MA==&appmsgid=10000220&itemidx=2&sign=62a8888bdb56bc268f255c020e024434'
            );
            $news[] = $img;  
          // $img = array(
          //   'Title'=>'用手机，登录【永不止息】^_^',
          //   'Description'=>'单图文 标题15字 摘要60字',
          //   'PicUrl'=>'http://www.yongbuzhixi.com/sites/default/files/pictures/picture-172-1356487827.jpg',
          //   'Url'=>'http://yongbuzhixi.com'
          // );
          //单图文 标题15字 摘要60字
          //多图文 1标题16字 2标题15字
          $wechatObj->news($news)->reply();
          break;
        case '500':
        case '５００':
          $title = '长夜的牵引';
          $musicurl = 'http://liangyou.nissigz.com/media/ws/ws'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '524':
        case '501':
        case '５２４':
        case '５０１':
          $title = '灵命日粮';
          $musicurl = 'http://liangyou.nissigz.com/media/bv/bv'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '5010':
        case '５０１０':
          // $title = '灵命日粮';
          $html = file_get_html('http://simplified-odb.org/');
          //get title
          $Title = trim($html->find('h1.entry-title', 0)->plaintext);
          // get body
          $Description = trim($html->find('.entry-content', 0)->plaintext);
          $Description .= "【5030】恋爱季节为您解读网络社交与圣经婚恋价值观";
          // Try to set your custom field
          $html = file_get_html('http://ya-mi.org/category/devotionals/odb/');
          $picture = $html->find('.homepost .thumb img', 0);

          $PicUrl = $picture->attr['src'];
          $img = array(
            'Title'=> $Title,
            'Description'=>$Description,
            'PicUrl'=>$PicUrl,
            'Url'=> 'http://simplified-odb.org'
          );
          $news[] = $img;
          $wechatObj->news($news)->reply();
          break;
        case '502':
        case '５０２':
          $title = '拥抱每一天';
          $musicurl = 'http://liangyou.nissigz.com/media/ee/ee'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '503':
        case '５０３':
          $title = '恋爱季节';
          $musicurl = 'http://liangyou.nissigz.com/media/se/se'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break; 
        case '5030':
        case '５０３０':
          $title = '婚姻很珍贵，婚前要预备';
          $musicurl = 'http://liangyou.nissigz.com/media/se/se130716.mp3';
          $desc = "解读网络社交与圣经婚恋价值观";
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break; 
        case '504':
        case '５０４':
          $title = '幸福满家园';
          $musicurl = 'http://liangyou.nissigz.com/media/bf/bf'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;    
        case '505':
        case '５０５':
          $title = '亲情不断电';
          $musicurl = 'http://liangyou.nissigz.com/media/up/up'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '506':
        case '５０６':
          $title = '欢乐卡洽碰';
          $musicurl = 'http://liangyou.nissigz.com/media/hg/hg'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '507':
        case '５０７':
          $title = '书香园地';
          $musicurl = 'http://liangyou.nissigz.com/media/bc/bc'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '508':
        case '５０８':
          $title = '晨曦讲座';
          $musicurl = 'http://liangyou.nissigz.com/media/ws/ws'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '509':
        case '５０９':
          $title = '生活无国界';
          $musicurl = 'http://liangyou.nissigz.com/media/gv/gv'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '510':
        case '５１０':
          $title = '无限飞行号';
          $musicurl = 'http://liangyou.nissigz.com/media/ib/ib'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '511':
        case '５１１':
          $title = 'i-radio爱广播';
          $musicurl = 'http://liangyou.nissigz.com/media/ir/ir'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '512':
        case '５１２':
          $title = 'i关怀心磁场';
          $musicurl = 'http://liangyou.nissigz.com/media/im/im'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '513':
        case '５１３':
          $title = '真理之光';
          $musicurl = 'http://liangyou.nissigz.com/media/th/th'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '520':
        case '５２０':
        // http://media.haomuren.org/dev/joy/joyhrt0716.mp3
          $title = '喜乐的心';
          $musicurl = 'http://media.haomuren.org/dev/joy/joyhrt'.date('md').'.mp3';
          // http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo130709.mp3
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;        
        case '521'://http://media.haomuren.org/dev/ev/evn0709.mp3
        case '５２１':
        // 荒漠甘泉乐侣
          $title = '荒漠甘泉乐侣';
          $musicurl = 'http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo'.date('ymd').'.mp3';
          // http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo130709.mp3
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '522':
        case '５２２':
          $title = '静夜亮光';
          $musicurl = 'http://media.haomuren.org/dev/ev/evn'.date('md').'.mp3';
          //http://media.haomuren.org/dev/ev/evn0709.mp3
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '523':
        case '５２３':
          $title = '在天父怀中';
          $musicurl = 'http://audio1.liangyou.net/files/media/ly_daily/2013Daily_'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '525':
        case '５２５':
          $title = '真道分解-每日灵修';
          $musicurl = 'http://media.biblexpo.net/biblexpo/daily/Daily_'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        default:
            if(substr($keyword, 0,2) == '91' && substr($keyword, 0,3) != '911') {
              $keyword = substr($keyword, 2);
              $keywords = explode('?', $keyword);

              if (!isset($keywords[1])) {
                $keywords = explode('？', $keyword);
              }
              if (!isset($keywords[1])) {
                $contentStr = "昵称后面缺少问号！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
              }else{
                $name = $keywords[0];
                if(strlen($keywords[1])!=4) {
                  $contentStr = "手机后四位信息【".$keywords[1]."】不正确！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
                  // break;
                }
                $error_msg = user_validate_name($name);
                if(strlen($error_msg)>0){
                  $contentStr = $error_msg;
                  // break;
                }
                $account = user_load_by_name($name);
                if(!$account) {
                  $contentStr = "不存在用户名【".$name."】！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
                  // break;
                }else {
                  $profile = profile2_load_by_user($account);
                  $tel = $profile['main']->field_telephone[LANGUAGE_NONE][0]['value'];
                  if(substr($tel, 7)!==$keywords[1]) {
                    $contentStr = "手机后四位信息【".$keywords[1]."】匹配不正确！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
                    // break;
                  }else {
                    //if bind,or not
                    $uid = mp_service_is_bind($account->uid);
                    if($uid) {
                      $contentStr = "用户名【".$account->name."】已绑定过！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
                      // break;
                    }else {
                      mp_service_bind_uid($FromUserName,$account->uid);
                      $contentStr = "恭喜您，【".$account->name."】绑定成功！！\n回复【00】进入主菜单";
                      // break;
                    }
                  }
                }
              } 
            } elseif (substr($keyword, 0,2) == '20') {
            //201+您想说的话
              $menukey = substr($keyword, 0, 3);//201-204
              $keyword = substr($keyword, 3);
              if(strlen($keyword) < 10 ) {
                $contentStr = "内容不能少于10字！";
              }else{
                $uid = mp_service_get_uid_by_name($FromUserName);
                if(!$uid) {
                  $contentStr = "您还没有与网站帐号绑定！\n回复【9】查看绑定帮助";
                }else{
                  $node = new stdClass();
                  $node->title = $keyword.'【来自微信】';
                  $node->type = 'photo';
                  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
                  $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
                  $node->uid = $uid;
                  $node->status = 1; //(1 or 0): published or not
                  $node->promote = 0; //(1 or 0): promoted to front page
                  $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
                  $node->path['pathauto'] = false;
                  // $node->body[$node->language][0]['value']   = $postObj->Content . print_r($postObj,true);
                  // $node->body[$node->language][0]['summary'] = text_summary($postObj->Content);
                  // $node->body[$node->language][0]['format']  = 'filtered_html';
                  // 【201】无主情话(随便说点情话)-38
                  // 【202】时光隧道(分享我的过去)-39
                  // 【203】独居生活(记录现在的生活)-40
                  // 【204】想对你说(写给喜欢的人)-41

                  $node->field_status_topic[$node->language][0]['tid'] = $menukey-163;
                  ////////begin @see love_layout_node_presave($node)
                   // $pattern = '/#([^\\#|.]+)#|＃([^\\＃|.]+)＃/';
                   // preg_match_all($pattern, $node->title, $matches, PREG_SET_ORDER);
                   // $node->field_status_tags[LANGUAGE_NONE] = array();
                   // foreach ($matches as $key => $value) {

                   //    $term_name = $value[1];
                   //    $term = taxonomy_get_term_by_name($term_name);
                   //    //new one
                   //    if(!count($term)){
                   //     $term = new stdClass();
                   //     $term->vid = 1;
                   //     $term->name = $term_name;
                   //     taxonomy_term_save($term);
                   //     //$term = taxonomy_get_term_by_name($term_name);
                   //     foreach ($term as $value) {
                   //        //dpm($value,$key);
                   //        $node->field_status_tags[LANGUAGE_NONE][$term->tid]['tid'] = $term->tid;
                   //      }
                   //    }else{
                   //      foreach ($term as $tid => $value) {
                   //        // dpm($value,$tid);
                   //        $node->field_status_tags[LANGUAGE_NONE][$tid]['tid'] = $tid;
                   //      }
                   //    }
                   // }
                  ///////////end
                  if($node = node_submit($node)) { // Prepare node for saving
                      node_save($node);//\n".$tip."
                      $contentStr = "恭喜您【".$keyword."】\n已经成功发布，查看已发布内容：http://www.yongbuzhixi.com";
                  }
                }
              }
              # code...
            } elseif (substr($keyword, 0,3) == '911') {
              $wechatObj->setFuncFlag(TRUE);
              $contentStr = "[Joyful]谢谢您的反馈，我们将慎重考虑您的意见和建议，请为本平台祷告，当然要给我祷告哦！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【911】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n【5030】恋爱季节为您解读网络社交与圣经婚恋价值观\n";
            }  elseif (substr($keyword, 0,3) == '119') {
              $wechatObj->setFuncFlag(TRUE);
              $contentStr = "[TearingUp]代祷事项已收到，主耶稣教导我们与哀哭的人同哭，愿照主的心意成就在你身上，阿门！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【911】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
            } elseif (substr($keyword, 0,3) == '900') {
              // $keyword = '900 gxk@mail.com name';
              $keywords = explode(' ', $keyword);
              watchdog('keywords', '<pre>'.print_r($keywords,TRUE), array(), WATCHDOG_NOTICE, 'link');
              if (!isset($keywords[2])) {
                 $contentStr = "内测申请格式不正确！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【911】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
              }elseif(!valid_email_address($keywords[1])){
                $contentStr = "邮箱不正确！\n回复【900 个人邮箱 姓名】申请内测,注意中间空格\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【911】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
              }elseif(isset(user_load_by_mail($keywords[1])->uid)){
                $contentStr = "该邮箱已注册！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【911】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
              }else{
                $wechatObj->setFuncFlag(TRUE);
                $contentStr = "内测申请已收到，管理员审核后，请耐心等待永不止息下一轮内测！\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【911】获得帮助\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";                
              }
            } else {
              $wechatObj->setFuncFlag(TRUE);
              $contentStr = "[TearingUp]对不起，我是机器人，还在努力学习中,暂不能识别本指令\n回复【00】进入主菜单\n回复【5】进入良友广播\n回复【911】获得帮助\n回复【110】推荐给好友？\n回复【911+意见建议内容】\n回复【5030】恋爱季节为您解读网络社交与圣经婚恋价值观\n永不止息，需要有你！\n官网：http://yongbuzhixi.com \n";
            }
          break;
      }
      $wechatObj->text($contentStr)->reply();
      exit;
      break;
    case Wechat::MSGTYPE_EVENT:
      // watchdog('MSGTYPE_EVENT', 'MSGTYPE_EVENT', array(), WATCHDOG_NOTICE, 'link');
      // $wechatObj->text("欢迎关注[Smile],我们将不定期发送永不止息最新动态给您~\n通过微信玩转永不止息？\n回复【00】进入主菜单\n所有功能测试开发中～敬请期待！")->reply();
      //preg to get key_words
      mp_service_focus();
      break;
    case Wechat::MSGTYPE_IMAGE:
      $FromUserName =  $wechatObj->getRev()->getRevFrom();
      $PicUrl =  $wechatObj->getRev()->getRevPic();
      $uid = mp_service_get_uid_by_name($FromUserName);
      watchdog('PicUrl'.$uid, $PicUrl, array(), WATCHDOG_NOTICE, 'link');
      if($uid) {
        $mp_service_records = mp_service_get_records($uid);
        db_update('mp_service')
          ->fields(array(
            'last_cmd' => 'image',
            'last_cmd_timestamp' => REQUEST_TIME,
          ))
          ->condition('uid', $uid)
          ->execute();
          watchdog('1', 'message', array(), WATCHDOG_NOTICE, 'link');
        if($mp_service_records['last_cmd'] == '20' && (REQUEST_TIME - $mp_service_records['last_cmd_timestamp'] > 900)) {
          $contentStr = "指令已超时！\n请回复【2】查看帮助！";
          $wechatObj->text($contentStr)->reply();
          exit;
        }
        watchdog('2', 'message', array(), WATCHDOG_NOTICE, 'link');
        if((REQUEST_TIME - $mp_service_records['last_cmd_timestamp'] <= 900)) {
          watchdog('3', 'message', array(), WATCHDOG_NOTICE, 'link');
          if($mp_service_records['last_cmd'] != '20') {
            watchdog('5', 'message', array(), WATCHDOG_NOTICE, 'link');
            $contentStr = "您发的图片想干什么呢？!\n请回复【2】查看帮助！";
            $wechatObj->text($contentStr)->reply();
            exit;
          }else {
            $contentStr = "发布成功！\n30秒内可回复文字添加照片描述\n如：【我爱北京！】";
            $wechatObj->text($contentStr)->reply();
            $node = new stdClass();
            $node->title = '【来自微信】';
            $node->type = 'photo';
            node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
            $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
            $node->uid = $uid;
            $node->status = 1; //(1 or 0): published or not
            $node->promote = 0; //(1 or 0): promoted to front page
            $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
            $node->path['pathauto'] = FALSE;
            $node->body[LANGUAGE_NONE][0]['value'] = '【来自微信】';
            $node->language = LANGUAGE_NONE;

            $path = $PicUrl.'.jpg';
            $filetitle = 'wechat';
            $filename = 'wechat-'.$uid.'-'.date("y-m-d").'.jpg';
            watchdog('6', 'message', array(), WATCHDOG_NOTICE, 'link');
            $file_temp = file_get_contents($path);//photos/
            watchdog('7', 'message', array(), WATCHDOG_NOTICE, 'link');
            $file_temp = file_save_data($file_temp, 'public://photos/'.$uid.'/'.$filename, FILE_EXISTS_RENAME);
            watchdog('8', 'message', array(), WATCHDOG_NOTICE, 'link');

            $node->field_photo = array(
              'und' => array(
                0 => array(
                    'fid' => $file_temp->fid,
                    'filename' => $file_temp->filename,
                    'filemime' => $file_temp->filemime,
                    'uid' => $uid,
                    'uri' => $file_temp->uri,
                    'status' => 1
                )
              )
            );
            watchdog('$node->field_photo', '<pre>'.print_r($node->field_photo,TRUE), array(), WATCHDOG_NOTICE, 'link');
            // $node->nid = 1;
            node_save($node);
            watchdog('node_save', $node->nid, array(), WATCHDOG_NOTICE, 'link');
            exit;

            // $wechatObj->text($contentStr)->reply();
            // mp_service_imageReplyText($contentStr);
          }
        }else {
          watchdog('4', 'message', array(), WATCHDOG_NOTICE, 'link');
          $contentStr = "指令超时！\n请回复【2】查看帮助！";
          $wechatObj->text($contentStr)->reply();
          exit;
        }

      }else {
        $contentStr = "您还没有与网站帐号绑定！暂不能发送图片！\n回复【9】查看绑定帮助";
        $wechatObj->text($contentStr)->reply();
        exit;
      }
      // $wechatObj->text("已收到您发送的图片！")->reply();
      break;
    default:
      $wechatObj->text("如需帮助，请加永不止息会员QQ群：322-1989-01\n测试开发中～敬请期待！")->reply();
  }
  return;



}

function mp_service_is_bind($uid) {
  $uid = db_query('SELECT uid FROM {mp_service} WHERE uid = :uid', array(':uid' => $uid))->fetchField();
  return $uid;
}
function mp_service_get_uid_by_name($FromUserName) {
  $uid = db_query('SELECT uid FROM {mp_service} WHERE fromusername = :fromusername', array(':fromusername' => $FromUserName))->fetchField();
  return $uid;
}
function mp_service_get_records($uid) {
  $res = db_query('SELECT * FROM {mp_service} WHERE uid = :uid', array(':uid' => $uid))->fetchAssoc();
  return $res;
}
function mp_service_get_nofakeid() {
  $res = db_query('SELECT * FROM {mp_service} WHERE fakeid = 0')->fetchAll();
  return (array)$res;
}

// and bind!
function mp_service_bind_uid($FromUserName,$bindUid) {
  $result = db_insert('mp_service')
    ->fields(array(
      'uid' => $bindUid,
      'fromusername' => $FromUserName,
      'created' => REQUEST_TIME,
    ))
    ->execute();
}

function mp_service_focus() {
  $postStr = $GLOBALS["HTTP_RAW_POST_DATA"];
  if (!empty($postStr)) {
    $postObj = simplexml_load_string($postStr, 'SimpleXMLElement', LIBXML_NOCDATA);
    // watchdog('mp-postObj', print_r($postObj,true), array(), WATCHDOG_NOTICE, 'link');
    //focus::SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1372159280 [MsgType] => event [Event] => subscribe [EventKey] => SimpleXMLElement Object ( ) )
    //receive::SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1372158829 [MsgType] => text [Content] => 看来 [MsgId] => 5893377295572656705 )
    $fromUsername = $postObj->FromUserName;
    $toUsername = $postObj->ToUserName;
    $keyword = trim($postObj->Content);
    $time = time();
    $textTpl = "<xml>
    <ToUserName><![CDATA[%s]]></ToUserName>
    <FromUserName><![CDATA[%s]]></FromUserName>
    <CreateTime>%s</CreateTime>
    <MsgType><![CDATA[%s]]></MsgType>
    <Content><![CDATA[%s]]></Content>
    <FuncFlag>0</FuncFlag>
    </xml>";   
    //subscribe begin我们将不定期发送永不止息最新动态给您~\n
    if($postObj->MsgType == 'event' && $postObj->Event == 'subscribe') {
      $contentStr = "欢迎关注[Smile]\n通过微信玩转永不止息？\n回复【00】进入主菜单\n回复【5】进入良友广播\n广播指令为纯数字，请勿带*号。号和中括号\n除广播内容外，所有功能测试开发中～敬请期待！";
      $msgType = "text";
      $resultStr = sprintf($textTpl, $fromUsername, $toUsername, $time, $msgType, $contentStr);
      echo $resultStr;
      exit;
    }
  }
}

function mp_service_imageReplyText($contentStr) {
  $postStr = $GLOBALS["HTTP_RAW_POST_DATA"];
  if (!empty($postStr)) {
    $postObj = simplexml_load_string($postStr, 'SimpleXMLElement', LIBXML_NOCDATA);
    watchdog('mp-postObj', print_r($postObj,true), array(), WATCHDOG_NOTICE, 'link');
    //SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1373499701 [MsgType] => image [PicUrl] => http://mmsns.qpic.cn/mmsns/ibiaMxQQytPZMjFUuLqe8eT1xibKw3apkMXqmCxqqTpmkGZQg7CnWoI5Q/0 [MsgId] => 5899136296960779666 [MediaId] => Gq6h5ZYJWPFtJkLuwryl5GNJOAdvnbwXOJFRGwItZbds_tHfNTxY3_x1A88f5vcd )
    $fromUsername = $postObj->FromUserName;
    $toUsername = $postObj->ToUserName;
    //
    $time = time();
    $textTpl = "<xml>
    <ToUserName><![CDATA[%s]]></ToUserName>
    <FromUserName><![CDATA[%s]]></FromUserName>
    <CreateTime>%s</CreateTime>
    <MsgType><![CDATA[%s]]></MsgType>
    <Content><![CDATA[%s]]></Content>
    <FuncFlag>0</FuncFlag>
    </xml>";
    if($postObj->MsgType == 'image') {
      $msgType = "text";
      $resultStr = sprintf($textTpl, $fromUsername, $toUsername, $time, $msgType, $contentStr);
      echo $resultStr;
      exit;
    }
  }
}