<?php
//
/**
 * Implements hook_menu().
 */
function mp_service_menu() {
  $items['mp_service'] = array(
    'title' => 'valid&response',
    'page callback' => 'mp_service_response',
    'access callback' => TRUE,
  );
  $items['admin/config/mp_service'] = array(
    'title' => 'mp_service settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mp_service_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mp_service.admin.inc',
  );
  return $items;
}

function my_module_function($last_reply_code=0) {
  global $user;
  $my_data = &drupal_static(__FUNCTION__);
  if (!isset($my_data)) {
    if ($cache = cache_get('mp_service_'.$user->uid)) {
      $my_data = $cache->data;
    }
    else {
      // Do your expensive calculations here, and populate $my_data
      // with the correct stuff..
      // cache_set('my_module_data', $my_data, 'cache');
      cache_set('mp_service_'.$user->uid, $my_data, 'cache_mp_service', time() + 60);//1分钟内回复有效
    }
  }
  return $my_data;
}

function mp_service_response() {
  module_load_include('inc', 'mp_service', 'mp_service');
  $options = array(
    'token'=> variable_get('mp_service_token', 'ybzx'),//填写你设定的key
  );
  $wechatObj = new Wechat($options);
  // $wechatObj->valid(); //注意, 应用验证通过后,可将此句注释掉, 但会降低网站安全性
  $type = $wechatObj->getRev()->getRevType();
  watchdog('mp_service：type', $type, array(), WATCHDOG_NOTICE, 'link');
  switch($type) {
    case Wechat::MSGTYPE_TEXT:
      $FromUserName =  $wechatObj->getRev()->getRevFrom();
      $keyword =  trim($wechatObj->getRevContent());
      switch ($keyword) {
        case '00':
          $contentStr = "【1】玩法介绍\n【2】发布相片/心情\n【3】查看最近活跃的弟兄姊妹\n【4】灵修广播\n【5】良友广播\n测试开发中～敬请期待！";
          break;
        case '1':
          $contentStr ="通过微信玩转永不止息？\n如果您有永不止息帐号\n请回复【9】绑定后更多玩法。\n回复【00】进入主菜单\n 测试开发中～敬请期待！";
          break;
        case '2':
          $contentStr = "【20】发布照片\n【21】想对你说(写给喜欢的人)\n【22】无主情话(随便说点情话)\n【23】时光隧道(分享我的过去)\n【24】独居生活(记录现在的生活)\n回复【00】进入主菜单\n 测试开发中～敬请期待！";
          break;
        case '3':
          $contentStr =  "【3】查看最近活跃的弟兄姊妹有：\n回复【00】进入主菜单\n 测试开发中～敬请期待！";
          break;
        case '4':
          $contentStr =  "【40】喜乐的心\n【41】荒漠甘泉乐侣\n【42】静夜亮光\n回复【00】进入主菜单\n回复【5】更多广播\n 测试开发中～敬请期待！";
          break;
        case '5':
          $contentStr =  "【50】长夜的牵引\n【51】灵命日粮\n【52】拥抱每一天\n【53】恋爱季节\n【54】拥抱每一天\n【54】欢乐卡洽碰\n【55】书香园地*\n【56】晨曦讲座\n【57】生活无国界\n【58】亲情不断电*\n【59】幸福满家园\n回复【00】进入主菜单 加*节目为周一到周五\n 测试开发中～敬请期待！";
          break;
        case '9':
          $contentStr =  "就要绑定，请回复\n【91昵称?手机后四位】 \n》比如：91活水泉?1407\n》91后面的为您的昵称。\n【900】如何查看用户昵称\n【901】如何查看手机信息";
          break;
        case '900':
          $contentStr =  "Q:如何查看用户昵称？\n A:首页点击右侧个人头像，进入个人页面，点击完善信息，在浏览器上看到一个数字就是你的ID，？\n回复【9】返回绑定菜单，回复【00】返回主菜单";
          break;
        case '901':
          $contentStr =  "Q:如何查看手机信息？\n A:一般注册的时候填写的\n如果在注册时没有填写，您可以到个人页面，点击：编辑->基本信息。\n回复【9】返回绑定菜单\n回复【00】返回主菜单";
          break;

        case '911':
          $contentStr =  "我很忙，但很愿意为您服务，请加bluesky_still把您使用到的问题发给我。\n回复【00】返回主菜单";
          break;
        case '110':
          $img = array(
            'Title'=>'hellohellohello',
            'Description'=>'hellohellohellohellohellohellohellohellohellohellohellohello',
            'PicUrl'=>'http://farm8.staticflickr.com/7362/9235198550_1f5973d4ec.jpg',
            'Url'=>'http://yongbuzhixi.com'
          );
          //单图文 标题15字 摘要60字
          //多图文 1标题16字 2标题15字
          $news[] = $img; 
          $news[] = $img; 
          $news[] = $img;
          $wechatObj->news($news)->reply();
          break;
        case '40':
          $title = '喜乐的心';
          $musicurl = 'http://media.haomuren.org/dev/joy/joyhrt'.date('md').'.mp3';
          http://media.haomuren.org/dev/joy/joyhrt0709.mp3
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '41'://http://media.haomuren.org/dev/ev/evn0709.mp3
        // 荒漠甘泉乐侣
          $title = '荒漠甘泉乐侣';
          $musicurl = 'http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo'.date('ymd').'.mp3';
          // http://media.HaoMuRen.org/Devotion/SID_MC/Jul/Dvo130709.mp3
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '42':
          $title = '静夜亮光';
          $musicurl = 'http://media.haomuren.org/dev/ev/evn'.date('md').'.mp3';
          //http://media.haomuren.org/dev/ev/evn0709.mp3
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '50':
          $title = '长夜的牵引';
          $musicurl = 'http://liangyou.nissigz.com/media/ws/ws'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '51':
          $title = '灵命日粮';
          $musicurl = 'http://liangyou.nissigz.com/media/bv/bv'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '52':
          $title = '拥抱每一天';
          $musicurl = 'http://liangyou.nissigz.com/media/ee/ee'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '53':
          $title = '恋爱季节';
          $musicurl = 'http://liangyou.nissigz.com/media/se/se'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;        
        case '54':
          $title = '欢乐卡洽碰';
          $musicurl = 'http://liangyou.nissigz.com/media/hg/hg'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '55':
          $title = '书香园地';
          $musicurl = 'http://liangyou.nissigz.com/media/bc/bc'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '56':
          $title = '晨曦讲座';
          $musicurl = 'http://liangyou.nissigz.com/media/ws/ws'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '57':
          $title = '生活无国界';
          $musicurl = 'http://liangyou.nissigz.com/media/gv/gv'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '58':
          $title = '亲情不断电';
          $musicurl = 'http://liangyou.nissigz.com/media/up/up'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        case '59':
          $title = '幸福满家园';
          $musicurl = 'http://liangyou.nissigz.com/media/bf/bf'.date('ymd').'.mp3';
          $desc = date('n月j日');
          $hgmusicurl = $musicurl;
          $wechatObj->music($title, $desc, $musicurl, $hgmusicurl)->reply();
          break;
        default:
            $contentStr = t('Thanks for your focus~,we will do our best for you!')."\n 测试开发中～敬请期待！";
            if(substr($keyword, 0,2)=='91') {
            $keyword = substr($keyword, 2);
            $keywords = explode('?', $keyword);

            if (!isset($keywords[1])) {
              $keywords = explode('？', $keyword);
            }
            $name = $keywords[0];
            if(strlen($keywords[1])!=4) {
              $contentStr = "手机后四位信息【".$keywords[1]."】不正确！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
              // break;
            }
            $error_msg = user_validate_name($name);
            if(strlen($error_msg)>0){
              $contentStr = $error_msg;
              // break;
            }
            $account = user_load_by_name($name);
            if(!$account) {
              $contentStr = "不存在用户名【".$name."】！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
              // break;
            }else {
              $profile = profile2_load_by_user($account);
              $tel = $profile['main']->field_telephone[LANGUAGE_NONE][0]['value'];
              if(substr($tel, 7)!==$keywords[1]) {
                $contentStr = "手机后四位信息【".$keywords[1]."】匹配不正确！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
                // break;
              }else {
                //if bind,or not
                $uid = mp_service_is_bind($account->uid);
                if($uid) {
                  $contentStr = "您的账户【".$account->name."】已绑定过！\n回复【9】查看绑定帮助\n如需帮助，请回复【911】";
                  // break;
                }else {
                  mp_service_bind_uid($FromUserName,$account->uid);
                  $contentStr = "恭喜您，【".$account->name."】绑定成功！！\n回复【00】进入主菜单";
                  // break;
                }
              }
            }
          }
          break;
      }
      $wechatObj->text($contentStr)->reply();
      break;
    case Wechat::MSGTYPE_EVENT:
      watchdog('MSGTYPE_EVENT', $type, array(), WATCHDOG_NOTICE, 'link');
      $wechatObj->text("欢迎关注\n通过微信玩转永不止息？\n回复【00】进入主菜单\n回复【5】快速进入良友广播电台\n我们将不定期发送永不止息最新动态给您~\n所有功能测试开发中～敬请期待！")->reply();
      break;
    case Wechat::MSGTYPE_IMAGE:
      $wechatObj->text("已收到您发送的图片！")->reply();
      break;
    default:
      $wechatObj->text("【1】玩法介绍\n【2】发布相片/心情\n【3】查看最近活跃的弟兄姊妹\n测试开发中～敬请期待！")->reply();
  }
  return;

  //preg to get key_words
  $postStr = $GLOBALS["HTTP_RAW_POST_DATA"];
        //extract post data
  if (!empty($postStr)) {
    $postObj = simplexml_load_string($postStr, 'SimpleXMLElement', LIBXML_NOCDATA);
    watchdog('mp-postObj', print_r($postObj,true), array(), WATCHDOG_NOTICE, 'link');
    //focus::SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1372159280 [MsgType] => event [Event] => subscribe [EventKey] => SimpleXMLElement Object ( ) )
    //receive::SimpleXMLElement Object ( [ToUserName] => gh_e7d44148423c [FromUserName] => oNAD2jlAk0ZGHkgezd_MnQbGrBPM [CreateTime] => 1372158829 [MsgType] => text [Content] => 看来 [MsgId] => 5893377295572656705 )
    $fromUsername = $postObj->FromUserName;
    $toUsername = $postObj->ToUserName;
    $keyword = trim($postObj->Content);
    $time = time();
    switch ($postObj->MsgType) {
        case 'text':
            $field_mp_type = 1;
            break;
        
        default:
            $field_mp_type = 2;
            break;
    }
    $textTpl = "<xml>
      <ToUserName><![CDATA[%s]]></ToUserName>
      <FromUserName><![CDATA[%s]]></FromUserName>
      <CreateTime>%s</CreateTime>
      <MsgType><![CDATA[%s]]></MsgType>
      <Content><![CDATA[%s]]></Content>
      <FuncFlag>0</FuncFlag>
      </xml>";

    //subscribe begin
    if($postObj->MsgType == 'event' && $postObj->Event == 'subscribe') {
      $contentStr = "欢迎关注[Smile],我们将不定期发送永不止息最新动态给您~\n通过微信玩转永不止息？\n回复【00】进入主菜单\n所有功能测试开发中～敬请期待！";
      $msgType = "text";
      $resultStr = sprintf($textTpl, $fromUsername, $toUsername, $time, $msgType, $contentStr);
      if(!mp_get_uid_by_FromUserName($fromUsername)) {
        //record the user in db
      }
      echo $resultStr;
      exit;
    }
    //subscribe end
    //
    if(!empty( $keyword )) {
      $msgType = "text";
      switch ($keyword) {
        case '00':
          $contentStr = "【1】玩法介绍\n【2】发布相片/心情\n【3】查看最近活跃的弟兄姊妹\n测试开发中～敬请期待！";
          break;
        case '1':
          $contentStr ="如果您在永不止息注册过，请回复9绑定后更多玩法。通过微信玩转永不止息？\n【1】玩法介绍\n【2】发布相片/心情\n【3】查看最近活跃的弟兄姊妹\n回复【00】进入主菜单\n 测试开发中～敬请期待！";
          break;
        case '2':
          $contentStr = "【20】发布照片\n【21】想对你说(写给喜欢的人)\n【22】无主情话(随便说点情话)\n【23】时光隧道(分享我的过去)\n【24】独居生活(记录现在的生活)\n\n回复【00】进入主菜单\n 测试开发中～敬请期待！";
          break;
        case '3':
          $contentStr =  "【3】查看最近活跃的弟兄姊妹有：\n回复【00】进入主菜单\n 测试开发中～敬请期待！";
          break;
        default:
            $contentStr = t('Thanks for your focus~,we will do our best for you!')."\n 测试开发中～敬请期待！";
          break;
      }
      $resultStr = sprintf($textTpl, $fromUsername, $toUsername, $time, $msgType, $contentStr);
        //生成本站订单begin

        // $node = new stdClass();
        // $node->title = $postObj->MsgId;
        // $node->type = 'mp_receive';
        // node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
        // $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
        // //todo:
        // //bind user
        // //mp_respone
        // //get_uid_by_FormUserName('oNAD2jlAk0ZGHkgezd_MnQbGrBPM');
        // $node->uid = 1;
        // $node->status = 1; //(1 or 0): published or not
        // $node->promote = 0; //(1 or 0): promoted to front page
        // $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
        // $node->path['pathauto'] = false;
        // $node->body[$node->language][0]['value']   = $postObj->Content . print_r($postObj,true);
        // $node->body[$node->language][0]['summary'] = text_summary($postObj->Content);
        // $node->body[$node->language][0]['format']  = 'filtered_html';

        // $node->field_mp_type['und'][0]['value'] = $field_mp_type;
        // $node->field_mp_fromusername['und'][0]['value'] = $postObj->FromUserName;
        // if($node = node_submit($node)) { // Prepare node for saving
        //     node_save($node);
        //     watchdog('mp-add mp-receive node', "Node with nid " . $node->nid . " saved!\n", array(), WATCHDOG_NOTICE, 'link');
        // }
        echo $resultStr;
        exit;

    }else{
      echo "Input something...";
      exit;
    }

    }else {
      echo "";
      exit;
    }

}

function mp_service_is_bind($uid) {
  $uid = db_query('SELECT uid FROM {mp_service} WHERE uid = :uid', array(':uid' => $uid))->fetchField();
  return $uid;
}

// and bind!
function mp_service_bind_uid($FromUserName,$bindUid) {
  $result = db_insert('mp_service')
    ->fields(array(
      'uid' => $bindUid,
      'fromusername' => $FromUserName,
      'created' => REQUEST_TIME,
    ))
    ->execute();     
  // $result = db_update('mp_service')
  //   ->fields(array(
  //     'uid' => $bindUid,
  //     // 'fromusername' => $FromUserName,
  //     // 'created' => REQUEST_TIME,
  //   ))
  //   ->condition('fromusername', $FromUserName)
  //   ->execute();
}