<?php
/**
 * Implements hook_menu().
 */
function ybread_menu() {
  $items['lingming'] = array(
    'title' => '灵命日粮',
    'page callback' => 'ybread_page',
    'type' => MENU_CALLBACK,
    // 'menu_name'=> 'main-menu',
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );
 $items['get_inhim'] = array(
    'title' => '灵命日粮',
    'page callback' => 'get_inhim',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'file' => 'ybread.page.inc',
  );

  return $items;
}

/**
 * Implements hook_cron().
 */
function ybread_cron() {
   /* Your code here */
   // $prefix = url(NULL, array('absolute' => TRUE)) . (variable_get('clean_url', 0) ? '' : '?q=');
   // $html = file_get_html($prefix.'lingming');
   // unset($html);
   module_load_include('inc', 'ybread', 'ybread.page');
   get_inhim();
   watchdog('ybread', 'ybread_cron', array(), WATCHDOG_NOTICE, 'link');
}