<?php
/**
 * Implements hook_block_info().
 */
function ybzx_block_info() {
	$blocks = array();
  //Introduce of this sites on user/* page .when not login.
  $blocks['video_endian'] = array(
    'info' => t('video_endian'),
    'cache' => DRUPAL_NO_CACHE, //to be confirmed
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    // 'pages' => 'node/371',
  );
  $blocks['video_endian_comments'] = array(
    'info' => t('video_endian_comments'),
    'cache' => DRUPAL_NO_CACHE, //to be confirmed
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    // 'pages' => 'node/371',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ybzx_block_view($delta = '') {
	 module_load_include('inc', 'love_layout', 'love_layout.block');
  $block = array();
  switch ($delta) {
  	case 'video_endian':
  		$html = file_get_html('http://v.tudou.com/_114352882/');
			  //get title $('[code]').attr('code')
			// $Title = trim($html->find('[code]', 0)->plaintext);
			// $Title = str_replace('查看','',$Title);
			// $Url =' http://www.tudou.com/programs/view/'.$html->find('[code]', 0)->attr['code'];
			$play_code = $html->find('[code]', 0)->attr['code'];
      $block['subject'] = NULL;//t('User info')
      $block['content'] = '<embed src="http://www.tudou.com/v/'.$play_code.'/&autoPlay=false/v.swf" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" wmode="opaque" width="480" height="400"></embed>';
  		break;
  	case 'video_endian_comments':
			$html = file_get_html('http://v.tudou.com/_114352882/');
			  //get title $('[code]').attr('code')
			$Title = trim($html->find('[code]', 0)->plaintext);
			$Title = str_replace('查看','',$Title);
			// $Url =' http://www.tudou.com/programs/view/'.$html->find('[code]', 0)->attr['code'];
			drupal_set_title($Title);
			$play_code = $html->find('[code]', 0)->attr['code'];
      $block['subject'] = NULL;//t('User info')
      $block['content'] = '<div style="overflow: hidden; margin: 15px auto; max-width: 671px;">
      <iframe scrolling="no" src="http://www.tudou.com/programs/view/'.$play_code.'" style="border: 0px none; margin-left: 0px; height: 2354px; margin-top: -853px; width: 926px;">
      </iframe>
      </div>';
  		break;
  	
  	default:
  		# code...
  		break;
  }
  return $block;
}

// This function adds a '+' next to each datebox with a link to the event node creation page,
// if the current user has permission to create events.
// Replace 'mymodule' with the name of your module.
// Replace 'event' with the name of your CCK content type.
function ybzx_preprocess_calendar_datebox(&$vars) {
  global $user;
  $content_types = array('grace365','in_him');
  $types = node_type_get_types();
  foreach ($content_types as $key => $content_type) {
    $last_node = _ybzx_get_last_node($content_type);
    $now = date('d',time());
    if(isset($last_node)) {
      $last = date('d',$last_node->created);
    }else{
      $last = $now -1;
    }
    if($vars['day'] == $now && $now - $last >= 1) {
      if (user_access('create '.$content_type.' content', $user)) {
          $vars['add_content_links'][] = l('+'.$types[$content_type]->name, 'node/add/'.str_replace('_', '-', $content_type));        
        }
    }  
  }
  
}

function  _ybzx_get_last_node($content_type = 'article') {// get latest node.
  $query = "SELECT n.nid nid, n.created created FROM {node} n  WHERE n.type = :type order by n.created desc limit 0,1";
  return db_query($query, array(':type' => $content_type))->fetch();
}


function ybzx_get_default_image_field_value($bundle = 'grace365', $field_name = 'field_image', $type = 'default_image', $entity_type = 'node') {
  $query = db_select('field_config_instance', 'fc');
  $query->fields('fc', array('id'));
  $query->condition('field_name', $field_name,'=');
  $query->condition('bundle', $bundle,'=');
  $query->condition('entity_type', $entity_type,'=');
  $id = $query->execute()->fetchField();

  $query = db_select('file_usage', 'fu');
  $query->fields('fu', array('fid'));
  $query->condition('type', $type,'=');
  $query->condition('id', $id,'=');
  $fid = $query->execute()->fetchField();
  $img = file_load($fid);
  
  $img = $img->uri;
  $img = file_create_url($img);
  return $img;
}