<?php
/**
 * Implements hook_block_info().
 */
function love_layout_block_info() {
  $blocks = array();
  $blocks['love_user_block'] = array(
    'info' => t('User info'),
    //'region' => 'sidebar_first',
  );
  //Introduce of this sites on user/* page .when not login.
  $blocks['sites_introduce'] = array(
    'info' => t('About Us'),
    'cache' => DRUPAL_NO_CACHE, //to be confirmed
    'region' => 'sidebar_second',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    //'pages' => 'user\r\nuser/login\r\nuser/register\r\nuser/password',
  );
  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function love_layout_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'love_user_block':
      $block['subject'] = NULL;//t('User info')
      $block['content'] = love_layout_user_block();
      break;
    case 'sites_introduce':
      $block['title'] = t('About Us');
        //Do not call menu_primary_local_tasks or menu_secondary_local_tasks because it does not output single item...
      $block['content'] = '
      <ul class="about-us">
        <li>1.我们坚信婚姻是神所设立的，是对我们幸福生活的美好设计。</li>
        <li>2.我们认为组建家庭是神对人的一项呼召，在家庭中彰显神的荣耀。</li>
        <li>3.基于圣经，我们认为神所设立的美好婚姻是：一男一女、一夫一妻、一生一世,信与不信原不相配。</li>
        <li>4.我们确信神在创世之先已未我们预备了另一半。</li>
        <li>5.我们相信神对我们的爱永不止息。</li>
      <div>【永不止息】只接受熟人间邮箱邀请注册，请为您邀请的肢体祷告，您在熟人之间互相介绍时，应慎重，严谨，并为之代祷。</div>
      <div>爱是永不止息，是互相激励成长，需要公众见证，公开交往，接受监督的，让更多的肢体在婚恋交友，及组建家庭上彰显神的荣耀</div>
      </ul>';//menu_local_tasks();
      break;
  }
  return $block;
}

/**
 * Get relate user info , context will be  used.
 */
function love_layout_user_block() {
  global $user;
  //TODO: 
  // if(arg(0) == 'user'){
  //   $account = user_load(arg(1));
  //   $account = $account->uid?$account:$user;
  // }else {
  //   $account = $user;
  // }
  // $account = $account->uid?$account:$user;
  $account = $user;
  $variables['account'] = $account;
  $variables['image_style'] = 'sc250';
  $picture = love_layout_template_preprocess_user_picture($variables);
  if($account->uid)
  $signature = $account->signature?$account->signature:"这家伙很懒，还没写签名....这家伙很懒，还没写签名....这家伙很懒，还没写签名....";
  $variables['account'] = $account;
  // '.l('<em class="icon-setting"></em>完善资料','user/'.$account->uid.'/edit/believes',array('html'=>TRUE,'attributes'=>array('class'=>'link-mt','target'=>"_blank"))).'
  //'.l('<em class="icon-upload"></em>进入相册','user/'.$account->uid.'',array('html'=>TRUE,'attributes'=>array('class'=>'link-mt','target'=>"_blank"))).'
  $output = '<div class="right-module module-selfInfo" data-log="userIntro">
            '.$picture.'
            <div class="module-selfInfo-inner">
               <div class="module-selfInfo-arrow">
                  <em class="icon-user-arrow"></em>
               </div>
               <div class="module-selfInfo-title">
                  <h2><a class="link-mt" data-log="nickname" target="_blank" href="/601017">'.$account->name.'</a></h2>
               </div>
               <div id="selfInfo" class="module-selfInfo-setting">
                  <ul>
                     <li>
                        <h3 class="text-md">个人资料</h3>
                        
                     </li>
                     <li class="noBg">
                        <h3 class="text-md">我的相册</h3>
                     </li>
                     <li>
                        <h3 class="text-md">我的缘分</h3>
                        <a class="link-mt" href="/followers" target="_blank">被收藏0</a>
                        <span class="text-sd fR" style="margin:-1px 3px 0;">|</span>
                        <a class="link-mt" href="/following" target="_blank">收藏<em class="js-following-count">7</em></a>
                     </li>
                  </ul>
               </div>
            </div>
         </div>';
  $output2 = '
  <div class="aside">
              <div class="info-box">
                  <div class="avatar">
                     '.$picture.'
                  </div>
                  <div class="description description-with-follow">
                    '.truncate_utf8($signature, $max_length=120, $wordsafe = FALSE, $add_ellipsis = TRUE, $min_wordsafe_length = 1).'

                  </div>
                  <div class="links links-with-follow">
                      <a href="">+熟人</a> /
                      '.l(t('Messages'),'messages/new/'.$account->uid,array('query' => drupal_get_destination())).' / 
                      '.l(t('Blog'),'user/'.$account->uid.'/blog',array('query' => drupal_get_destination())).' / 
                      <a href="">+粉丝</a>
                  </div>
                  
                  <div class="follow">
                  '._love_user_relationships_link($variables).'
                  </div>
                  
              </div>
          </div>';
         
  return $output;//.drupal_render(menu_local_tasks());
}


//TODO 定制最近来访 主题9宫格
/**
 * Implements hook_block_view().
 * @see user_visits_adv_block_view($delta = '')
 */
/**
* Implementation of hook_block_view_MODULE_DELTA_alter
*/
function love_layout_block_view_alter(&$data, $block) {

  if($block->delta == 'my_latest_visitors'){
    global $user;
    $limit = variable_get('user_visits_block_items_' . $block->delta, 8);
    $data['content'] =  user_visits_display_block_4love($user->uid, $limit);
  }

  if( $block->delta == 'latest_visitors'){
      //$block['subject'] = t('Latest visitors');
      //$block['content'] = user_visits_display_block_1(NULL, $limit);
      //dpm($block,'block');
      //$data['content'] = 'nothings';
      //dpm($data,'data'); 
  }
    
}
/**
 * Get latest visitors for block content
 */
function user_visits_display_block_4love($uid = NULL, $limit = 8) {
  $output = "";
  if (!$uid && (arg(0) == 'user' && is_numeric(arg(1)))) {
    $uid = arg(1);
  }

  if ($uid) {
    $visitors = user_visits_latest($uid, $limit); 
    $output .= '<div class="clearfix recent-visits">';
    if (is_array($visitors)) {
      foreach ($visitors as $visitor) {
        $account = user_load($visitor->vuid);
        $output .= theme('user_visits_4love', array('account' => $account, 'timestamp' => $visitor->visit));
      }
    }
    $output = theme('user_visits_total', array('total' => user_visits_total($uid))).$output;
    $output .= '</div>';
  }

  return $output;
}
/**
 * Implements of hook_theme().
 */
function love_layout_theme($existing, $type, $theme, $path) {
  return array(
    'user_visits_4love' => array(
      'variables' => array(
        'account'   => NULL,
        'timestamp' => NULL,
        'referer'   => NULL,
      ),
    ),
  );
}

/**
 * Themeable function.
 */
function theme_user_visits_4love($account, $timestamp = NULL, $referer = NULL) {
  $output  = '<div class="recent-visit">' . "\n";
  //$output .= theme('user_picture', array($account));

  $output .= love_layout_template_preprocess_user_picture($account);
  $output .= ' <div class="name">' . theme('username', $account) . '</div>' . "\n";
  /*if ($account['timestamp']) {
    $output .= $account['timestamp'] ? ' <div class="visit">' . t('!time ago', array('!time' => format_interval(REQUEST_TIME - $account['timestamp']))) . '</div>' . "\n" : '';
    $output .= $account['referer'] ? ' <div class="referer">' . t('Referer !link', array('!link' => l($account['referer'], $account['referer']))) . '</div>' . "\n" : '';
  }*/
  $output .= '</div>' . "\n";
  return $output;
}


/**
 * Process variables for user-picture.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $account: A user, node or comment object with 'name', 'uid' and 'picture'
 *   fields.
 *
 * @see user-picture.tpl.php
 * @see template_preprocess_user_picture
 */
function love_layout_template_preprocess_user_picture($variables) {
  $variables['user_picture'] = '';
  if (variable_get('user_pictures', 0)) { 
    $account = $variables['account'];
    if (!empty($account->picture)) {
      // @TODO: Ideally this function would only be passed file objects, but
      // since there's a lot of legacy code that JOINs the {users} table to
      // {node} or {comments} and passes the results into this function if we
      // a numeric value in the picture field we'll assume it's a file id
      // and load it for them. Once we've got user_load_multiple() and
      // comment_load_multiple() functions the user module will be able to load
      // the picture files in mass during the object's load process.
      if (is_numeric($account->picture)) {
        $account->picture = file_load($account->picture);
      }
      if (!empty($account->picture->uri)) {
        $filepath = $account->picture->uri;
      }
    }
    elseif (variable_get('user_picture_default', '')) {
      $filepath = variable_get('user_picture_default', '');
    }
    if (isset($filepath)) {
      //$alt = t("@user's picture", array('@user' => format_username($account)));
      $alt ='';
      if(isset($variables['timestamp']))
      $alt = $variables['timestamp'] ?  t('!time ago', array('!time' => format_interval(REQUEST_TIME - $variables['timestamp']))) : '';
      // If the image does not have a valid Drupal scheme (for eg. HTTP),
      // don't load image styles.

      if (module_exists('image') && file_valid_uri($filepath) && $style = variable_get('user_picture_style', '')) {
        $style = isset($variables['image_style'])?$variables['image_style']:$style;
        $variables['user_picture'] = theme('image_style', array('style_name' => $style, 'path' => $filepath, 'alt' => $alt, 'title' => $alt));
      }
      else {
        $variables['user_picture'] = theme('image', array('path' => $filepath, 'alt' => $alt, 'title' => $alt));
      }
      if (!empty($account->uid) && user_access('access user profiles')) {
        $attributes = array('attributes' => array('title' => t('View user profile.')), 'html' => TRUE);
        $variables['user_picture'] = l($variables['user_picture'], "user/$account->uid", $attributes);
      }
    }
    return $variables['user_picture'];
  }
}

/**
 * Get latest visitors for block content.
 * @see user_visits_adv_visitors_block()
 */
function _love_user_visits_adv_visitors_block($limit = 8) {
  global $user;
  $output = '';

  if ($user->uid) {
    $visitors = user_visits_adv_get('visitors', $user->uid);
    if (is_array($visitors)) {
      $visitors = array_slice($visitors, 0, $limit, TRUE);
      foreach ($visitors as $uid => $visit) {
        $account = db_query('SELECT uid, name, picture FROM {users} WHERE uid = :uid', array(':uid' => $uid))->fetchObject();
        $output .= theme('user_visits', array('account' => $account, 'visit' => $visit));
      }
    }
  }
  return $output;
}

/**
 * Implements hook_modules_installed().
 *
 * @see devel_install()
 */
function love_layout_modules_installed($modules) {
  if (in_array('menu', $modules)) {
    $menu = array(
      'menu_name' => 'love',
      'title' => t('Love menu'),
      'description' => t('Love Navigation Menu'),
    );
    menu_save($menu);
  }
}

function _statuses_page($account) {
  $account = user_load($account);
  $output = theme('statuses_form_display', array('recipient' => $account, 'type' => 'user'));
  return $output;
}

/**
 * Implements hook_menu().
 */
function love_layout_menu() {
  $items = array();
  $items['user/%/statuses'] = array(
    'title' => t('Statuses'),
    'description' => 'User statuses.',
    'page callback' => '_love_statuses_user_view',
    'page arguments' => array(1),
    'access arguments' => array('Update and view own stream'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
/**
 * Implements hook_user_view().
 * @see statuses_user_view()
 */
function _love_statuses_user_view($account) {
  if (variable_get('statuses_profile', 1)) {
    $account = user_load($account);
    $value = theme('statuses_form_display', array('recipient' => $account, 'type' => 'user'));
    // Don't show this section if there's nothing there or the user doesn't have permission to see it.
    if (empty($value)) {
      return;
    }
    if (!isset($account->content['statuses'])) {
      $account->content['statuses'] = array();
    }
    $account->content['statuses'] += array(
      '#type' => 'user_profile_category',
      '#attributes' => array('class' => array('statuses-profile-category')),
      '#weight' => -5,
      '#title' => t('Messages'),
    );
    $account->content['statuses']['status'] = array(
      '#type' => 'user_profile_item',
      '#title' => '',
      '#markup' => $value,
      '#attributes' => array('class' => array('statuses profile')),
    );
    return $account->content['statuses'];
  }
}
//$value = theme('statuses_form_display', array('recipient' => $account, 'type' => 'user'));
function love_layout_menu_alter(&$items) {

  //$items['publish'] = $items['node/add/photo'];
  $items['node/add/photo']['title'] = t('+');
  $items['node/add/photo']['menu_name'] = 'main-menu';

  // Example - disable the page at node/add
  $items['messages']['title callback'] = 'privatemsg_title_callback_alter';
  $items['messages/recent'] = $items['messages'];
  $items['messages/recent']['menu_name'] = 'love';
  $items['messages/recent']['title'] = t('Messages');
  //$items['messages/recent']['title callback'] = 'privatemsg_title_callback_alter';


  $items['user']['title'] = t('Myspace');
  $items['user']['menu_name'] = 'love';
  $items['user']['access callback'] = 'user_is_logged_in';

  $items['publish/photo'] = $items['node/add/photo'];
  $items['publish/photo']['title'] = t('上传相片');
  $items['publish/photo']['menu_name'] = 'love';

  $items['invite/others'] = $items['invite'];
  
  $items['invite/others']['title'] = t('邀请熟人');
  $items['invite/others']['menu_name'] = 'love';

  $items['relationships/my'] = $items['relationships'];
  $items['relationships/my']['menu_name'] = 'love';
  $items['relationships/my']['title'] = t('My acquaintances');//熟人

  $items['relationships/my'] = $items['relationships'];
  $items['relationships/my']['menu_name'] = 'love';
  $items['relationships/my']['title'] = t('My acquaintances');//我想认识的

  $items['relationships/my'] = $items['relationships'];
  $items['relationships/my']['menu_name'] = 'love';
  $items['relationships/my']['title'] = t('I am a acquaintance of');//我想认识的
//熟人申请 Sent requests
//发出申请 Received requests
//你们是熟人==
  //加认识 男-女
  //-认识
  //互相认识 转角缘分 
//http://drupal.org/node/1336212#comment-6049694 bug fix when node_add_form in addtional
   $items['file/ajax']['file'] = 'node.pages.inc';
   $items['file/ajax']['file path'] = drupal_get_path('module', 'node');
}
/**
 * multilanguage t() for message.
 * @see privatemsg_title_callback()
 */
function privatemsg_title_callback_alter($title = NULL) {
  $count = privatemsg_unread_count();

  if ($count > 0) {
    //return format_plural($count, 'Messages (1 new)', 'Messages (@count new)');
    return format_plural($count, t('Messages (1 new)'), t('Messages (@count new)'));
  }
  return t('Messages');
}
/**
 * Implements hook_admin_path().
 */
function love_layout_admin_paths_alter(&$paths) {
  $paths['user/*/edit'] = FALSE;
  $paths['user/*/edit/main'] = FALSE;
  $paths['user/*/edit/believe'] = FALSE;

  $paths['node/add/*'] = FALSE;
  $paths['node/*/delete'] = FALSE;
    
}

function love_layout_preprocess_page(&$variables) {
 /* $headers = drupal_get_http_header();

  if (preg_match('@HTTP/1\.[01]\x20+403@', $headers)) {
    $variables['body_classes'] .= 'error-403,';
  }
  elseif (preg_match('@HTTP/1\.[01]\x20+404@', $headers)) {
    $variables['body_classes'] .= 'error-404,';
  }  */
  //module_load_include('inc', 'love_layout', 'love_layout.customs'); 
  module_load_include('inc', 'node', 'node.pages'); 
  module_load_include('inc', 'love_layout', 'love_layout.customs');  
  $variables['add_photo'] = _node_add4love('photo');
  //feedback of webform.
  $node = node_load(19);
  $variables['feedback'] = _node_page_view4love($node);

}

function love_layout_form_alter(&$form, &$from_state, $form_id) {
  if($form_id == 'privatemsg_new') {
    $form['subject']['#access'] = FALSE;
  }
  if($form_id == 'webform_client_form_19') {
    $form['submitted']['email']['#access'] = FALSE;
  }
  if($form_id == 'photo_node_form'){
   // dpm($form);
  }
}
// when the bug of i18n + og_field   resolve ,can user below.
//http://drupal.org/project/issues/og?text=i18n&status=All&priorities=All&categories=All&version=7.x&component=All
/**
 * hook_form_FORM_ID_alter(&$form, &$form_state, $form_id)
 * when add a new photo,set  group audience default love.
 */
function love_layout_form_photo_node_form_alter(&$form, &$form_state, $form_id) {
 // $form['og_group_ref']['#access'] = FALSE;
  /*
  $options = $form['og_group_ref'][LANGUAGE_NONE][0]['default']['#options'];
  //2 is the love group gid.
  $form['og_group_ref'][LANGUAGE_NONE][0]['default']['#default_value'] = $options[2];*/

  // hidden some function now,body and tags 分享感言 标签功能暂不开放

  $form['body']['#access'] = FALSE;
  $form['field_tags']['#access'] = FALSE;
  $form['og_group_ref']['#access'] = FALSE;
  drupal_add_js(drupal_get_path('module','love').'/js/love-photo-add.js');
}



/**
 * Implements hook_user_view().
 * @see statuses_user_view()
 */
function love_layout_user_view_alter(&$build) {
  $build['privatemsg_send_new_message']['#access'] = FALSE;
  global $user;
  if(arg(1)){
    $ac = user_load(arg(1));
    if($user->uid == $ac->uid){
      //$build['privatemsg_send_new_message']['#access'] = FALSE;
      
    }else{
      $build['summary']['#access'] = FALSE;
    }
  }
  //drupal_add_css(drupal_get_path('module', 'love_layout').'/css/profiles.css');
  if (variable_get('statuses_profile', 1)) {
    if (isset($build['statuses'])) {
      unset($build['statuses']);
      //$build['statuses']['#access'] = FALSE;
    }
  }
}




/**
 * Implements hook_preprocess_author_pane().
 * @see function user_relationships_preprocess_author_pane(&$variables) {
 *  $variables['account']
 */
function _love_user_relationships_link($variables) {
  // Check if this preprocess needs to be run given who's calling it.
  $output = '';
  global $user;
  $account = $variables['account'];

  // Anonymous users and users viewing their own account won't get a link.
  if (!$user->uid || !$account->uid || $user->uid == $account->uid) {
    return $output;
  }
  // Get a list of selected relationship types
  $all_rtypes = user_relationships_types_load();

  foreach ($all_rtypes as $rtype) {
    $relationships = user_relationships_load(array('requester_id' => $user->uid, 'requestee_id' => $account->uid, 'rtid' => $rtype->rtid));

    if (count($relationships)) {
      // Existing relationship; need remove icon/link. (Despite the foreach,
      // there should only be one.)
      foreach ($relationships as $relationship) {
        $link_label = t('Remove @name from @rel_plural_name', array('@name' => format_username($account), '@rel_plural_name' => $relationship->plural_name));
        $css_class = array(str_replace(' ', '-', $relationship->name), 'author-pane-link', 'user_relationships_popup_link', 'author-relationship-remove-icon');
        //link to remove
        if (!isset($variables['user_relationships'])) {
          $variables['user_relationships'] = '';
        }
        $variables['user_relationships'] .= '<div class="author-pane-ur-link-item">';
        $variables['user_relationships'] .=
          l('<span>' . t('Remove @rel_name', array('@name' => format_username($account), '@rel_name' => ur_tt("user_relationships:rtid:$relationship->rtid:name", $relationship->name))) . '</span>',
          "user/{$user->uid}/relationships/{$relationship->rid}/remove",
          array(
                'query' => drupal_get_destination(),
                'html' => TRUE,
                'attributes'  => array('title' => $link_label, 'class' => $css_class),
          ));
        $variables['user_relationships'] .= '</div>';
      }
    }
    else {
      //No existing relationship; need an add icon/link.
      if (!user_relationships_can_request($user, $rtype) || !user_relationships_can_receive($account, $rtype)) {
        continue;
      }
      $css_class = array(str_replace(' ', '-', $rtype->name), 'author-pane-link', 'user_relationships_popup_link', 'author-relationship-remove-icon');
      //add link
      if (!isset($variables['user_relationships'])) {
        $variables['user_relationships'] = '';
      }
      $variables['user_relationships'] .= '<div class="author-pane-ur-link-item">';
      $variables['user_relationships'] .=
        l('<span>' . t('Add @rel_name', array('@name' => format_username($account), '@rel_name' => ur_tt("user_relationships:rtid:$rtype->rtid:name", $rtype->name))) . '</span>',
          "relationship/{$account->uid}/request/{$rtype->rtid}",
          array(
            'query' => drupal_get_destination(),
            'html' => TRUE,
            'attributes'  => array(
              'title' => t('Become @name\'s @rel_name', array('@name' => format_username($account), '@rel_name' => ur_tt("user_relationships:rtid:$rtype->rtid:name", $rtype->name))),
              'class' => $css_class
            ),
          )
        );
      $variables['user_relationships'] .= '</div>';
    }
    //$output .= $variables['user_relationships'];
  }
  return $variables['user_relationships'];
}

